# PORT
server:
  port: 8082

# EUREKA REGISTRATION
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# DATASOURCE
spring:
  application:
    name: user-service
    
#   datasource:
#     url: jdbc:postgresql://localhost:5432/user
#     username: postgres
#     password: Elvans@0309
#     driver-class-name: org.postgresql.Driver

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:mujiki_user
    username: mujiki_user
    password: nothing

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
  liquibase:
    change-log: classpath:sql/db.changelog-master.xml
    enabled: true
  security:
    jwt:
      secret: xxdWXHtgXeXs0vaLSRjrORGDZvuRSoRHEOc43IyiLl6YOOjTW5U11Ae0fRA0vyeAHqOvepKwiHTkB/dLZP+ESw== # base64 secret
      expiration: 43200000
  sql:
    init:
      mode: never

# DOMAIN ALLOWED ORIGINS
frontend:
  domain:
    url: http://localhost:5173